### ISSUE TITLE
CRUD Hotels

### ISSUE THREAD

**Issue by LinnierGames** [Breezy-Traveler/Breezy-iOS#151]
- [x] Display Hotels for the selected Trip
- [x] Create Hotels for the selected Trip
- [x] Update Hotels for the selected Trip
- [x] Delete Hotels for the selected Trip

## Todo

- [x] Test with real data vs mock
