### ISSUE TITLE
CRUD Sites

### ISSUE THREAD

**Issue by LinnierGames** [Breezy-Traveler/Breezy-iOS#152]
- [x] Display Sites for the selected Trip
- [x] Create Sites for the selected Trip
- [x] Update Sites for the selected Trip
- [x] Delete Sites for the selected Trip

## Todo

- [x] Test with Inherited Vc

**Comment by phylliswong** [comment]
completed
