### ISSUE TITLE
Detailed View Controller of a Trip

### ISSUE THREAD

**Issue by LinnierGames** [Breezy-Traveler/Breezy-iOS#37]
### Todo

- [x] segue to the view controller 
- [x] modify trip.place
- [x] modify trip.isPublished
